### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by greenboxal** [c0b/docker-erlang-otp#110]
Last update of `elixir:1.5` with `erlang:20` broke SSL.

We started getting random `{:tls_alert, :bac_mac_record}` errors when talking with HTTPS services. Rolling back to `erlang:20.2.3` solves the issue.

Seems like the base image is broken as when using `apt-get` with it you get a lot of errors related to bad ELF files.

**Comment by c0b** [comment]
not reproducing here; do you have more logs

>  Seems like the base image is broken as when using apt-get with it you get a lot of errors related to bad ELF files.

especially this one would be more severe if reproducible; are you sure the bad ELF files only happen with erlang images? also tried with debian base images?

**Comment by c0b** [comment]
please re-check after https://github.com/c0b/docker-erlang-otp/issues/121#issuecomment-384761214

if can still reproduce, please report to the new https://github.com/erlang/docker-erlang-otp Thanks
