### ISSUE TITLE
Upgrade to Debian Stretch 9.0

### ISSUE THREAD

**Issue by alessandrolattao** [c0b/docker-erlang-otp#114]
We use rsyslog to handle system logs inside docker containers but the version included in Debian 8.0 is old and configuration syntaxes are slightly different.
It would be great if you could upgrade to the latest stable version of Debian.
Thank you.

**Comment by c0b** [comment]
are you using the Erlang 20 or 19? the Erlang 20 Dev branch is already on Debian Stretch for a while and we could upgrade the other slim images on Debian Stretch as well.

for even older Erlang versions I am intended to let them as is, but I am open for different opinions; we can let #115 open for a couple of days for discussions

**Comment by c0b** [comment]
@alessandrolattao could you comment which Erlang were you using? from the CI build in #115 it seems the Erlang19 doesn't build with Debian 9's default libssl1.0.2 library, `ssl, ssh, crypto` these Erlang apps won't build, affected rebar failed to build, many other apps depended on won't work as well; for example the https, this is an essential part of nowadays Internet applications we can't live without;
And this is upstream don't want to support libssl1.0.2+ above; I don't think we need to support; Please upgrade to Erlang 20 if you were on 19.
