### ISSUE TITLE
include tk graphical libraries for observer

### ISSUE THREAD

**Issue by c0b** [c0b/docker-erlang-otp#28]
the original goal for this repo was to deliver an Erlang container as close as possible to upstream (https://github.com/erlang/otp/releases) within reasonable image size, it turns out to be the current approach: download source code tarball from upstream, and compile it during building the docker image, this way we can control 3rd party library dependencies as minimum and most often used ones; so that it didn't pull in all java for jinterface, and gtk/gl for wxwidgets (which is a required dependency for observer to start, see observer source code at https://github.com/erlang/otp/tree/maint/lib/observer/src, it is a wxwidgets application.)

Now @AugustoPedraza is requesting to use observer (see c0b/docker-elixir#19 for background), it is totally possible to include gtk/gl for wxwidgets during the compiling; the only question is should we do it? or maintain another variant?

@sdwolf gives another example of using the precompiled packages from erlang-solutions: https://github.com/c0b/docker-elixir/issues/19#issuecomment-257648388
I was aware of this approach but didn't choose it since the beginning of this project was because they were not releasing as often as today, there was some lags behind erlang upstream, but now in 2016 it seems ok, from erlang-solutions we can get pretty latest once every upstream release, we can have a image size test and it's probably ok to switch

The other approach was to use OS/Distro pre-packages many Linux distros were packaging Erlang very trivial https://packages.debian.org/jessie/erlang and not preferred,
https://packages.debian.org/sid/erlang https://packages.debian.org/jessie-backports/erlang

Please vote here what changes you want to see in the Erlang base image.

**Comment by sdwolf** [comment]
I vote with compiling from source and adding the dependencies for observer, but only in the default image and not in the slim version. This looks like the cleanest solution for me. 

Using the binaries from Erlang Solution should be a last resort, from what I remember it takes them a bit (2-3 days) to publish newer versions and this does not satisfy my bleeding edge desires :smile:, plus you need to install a lot of packages for it. Also Dockerfiles are a great resource if you want to learn how to install things from source and I'd prefer if we keep it like that.

Now, a reason for why should we do it, while I do not use observer yet in my development cycle, everywhere that I went to see a presentation about erlang/elixir the presenter would fire up a shell and start observer to brag about it's awesomeness. So it looks to me like it's perceived as a feature of Erlang and not as an extra tool.
