### ISSUE TITLE
enable dirty-scheduler on default erlang image

### ISSUE THREAD

**Issue by c0b** [c0b/docker-erlang-otp#29]
I just found a comment on the docker hub page https://hub.docker.com/_/erlang/

> radupopescu   18 days ago
> Hello,
> Would it be possible to enable dirty schedulers for 19, 19.1, latest images?

and researched somewhat for benefits why need dirty scheduler and how to do that

https://news.ycombinator.com/item?id=11064763
https://hamidreza-s.github.io/erlang/scheduling/real-time/preemptive/migration/2016/02/09/erlang-scheduler-details.html

http://erlang.org/doc/installation_guide/INSTALL.html#Advanced-configuration-and-build-of-ErlangOTP_Configuring

> --enable-dirty-schedulers - Enable the experimental dirty schedulers functionality. Note that the dirty schedulers functionality is experimental, and not supported. This functionality will be subject to backward incompatible changes. Note that you should not enable the dirty scheduler functionality on production systems. It is only provided for testing. This switch also imply --enable-new-purge-strategy (see below).

the good news is this feature would be an easy one https://github.com/c0b/docker-erlang-otp/blob/master/19/Dockerfile#L24 just need some sanity check before releasing in the new way of building 19+ images

(generally a github issue for feature request is preferred over docker hub comment, because hub.docker.com doesn't have comments notification and many other features as a discussion board should have)

**Comment by c0b** [comment]
another good one: https://medium.com/@jlouis666/erlang-dirty-scheduler-overhead-6e1219dcc7

**Comment by radupopescu** [comment]
Thanks for the links and for updating the image. Waiting for #29.

About the dockerhub comments, understood.

**Comment by radupopescu** [comment]
Hi there,

I was wondering if you know when this will be merged? Having dirty schedulers enabled in the Erlang 19 image would greatly simplify my other image(s).

Thanks!

**Comment by c0b** [comment]
sorry didn't have a chance to update, while doing #32 I did some local test of enabled dirty scheduler, it works without too much effort; so another PR to enable dirty scheduler should be there shortly

**Comment by radupopescu** [comment]
Hi!

This is great to hear. Looking forward to trying out the new image.

Thanks!
