### ISSUE TITLE
Move out Elixir to another repo

### ISSUE THREAD

**Issue by vovimayhem** [c0b/docker-erlang-otp#3]
I suggest we extract out the Elixir Dockerfile to a new repo. This way, the elixir upstream team would define the repo collaborators independently from the erlang project.

Join the discussion at https://github.com/docker-library/official-images/issues/1171

**Comment by c0b** [comment]
for sure it can be in a separate repo; but current phase is anyone know how to push docker-library/official-images#1075 to be merged ? become official ? then make another PR for Dockerfile for elixir is easy.

**Comment by vovimayhem** [comment]
True that. Will refer to your repo until makes more sense to extract it

**Comment by c0b** [comment]
this is done in elixir image:

1. https://github.com/c0b/docker-elixir
2. https://hub.docker.com/_/elixir/
