### ISSUE TITLE
Include hex.pm and rebar on erlang images.

### ISSUE THREAD

**Issue by vovimayhem** [c0b/docker-erlang-otp#4]
It looks like a good idea to bundle these on the erlang images, just as `bundler` is bundled in the ruby image.

**Comment by vovimayhem** [comment]
Once included, we could do something useful with those 'onbuild' Dockerfiles :)

**Comment by c0b** [comment]
I have included both rebar & rebar3 `erlang:18` images; let's see how can it be used with onbuild ?

https://hub.docker.com/_/erlang/
https://github.com/c0b/docker-erlang-otp/blob/master/18/onbuild/Dockerfile

**Comment by vovimayhem** [comment]
Cool!!!!
