### ISSUE TITLE
Revised onbuild images

### ISSUE THREAD

**Issue by tsloughter** [c0b/docker-erlang-otp#47]
I was trying out multi-stage builds and wanted to create a generic onbuild image others could use to build their minimal release images.

I think this would be a more appropriate `onbuild` set of instructions that what current exists:

```
ONBUILD WORKDIR /usr/src/app
ONBUILD COPY . /usr/src/app
ONBUILD RUN rebar3 as prod tar

ONBUILD RUN mkdir -p /opt/rel
ONBUILD RUN tar -zxvf /usr/src/app/_build/prod/rel/*/*.tar.gz -C /opt/rel
```

The use of `tar` is important because of how Erlang target systems are built that changes around a few things from just the built release and use of the `prod` profile so the user can specify how they want their project built for production.

Then the user can make their `Dockerfile` (with docker 17.05 and above):

```
FROM erlang:19.3.3-onbuild as builder

FROM ubuntu:16.04

ENV RELX_REPLACE_OS_VARS true
<any ENV vars they want defaults set of>

WORKDIR /opt/<RELEASE NAME>
COPY --from=builder /opt/rel /opt/<RELEASE NAME>
ENTRYPOINT ["/opt/<RELEASE NAME>/bin/<RELEASE NAME>"]
```

What do you think?

**Comment by c0b** [comment]
are you aware of https://github.com/docker-library/docs/pull/911/files it seems many users want to customize ONBUILD process but it doesn't have the flexibility

> +The `ONBUILD` image variants are deprecated, and their usage is discouraged. For more details, see [docker-library/official-images#2076](https://github.com/docker-library/official-images/issues/2076).

I was keeping 19/onbuild/ directory only for travis-ci, but after I redesigned .travis-ci.yaml process the onbuild/ directory is no longer needed;

For your showed case, I agree it could be a good one, from above docker-library# the recommended way is we may document it as a good minimal example of using multi-stage build, it's just like for end users to copy all ONBUILD instructions

```dockerfile
FROM erlang:19 as builder
# copy all ONBUILD instructions here

FROM ubuntu:16    # or from alpine:3.6
COPY --from=builder /opt/rel ...
```

**Comment by tsloughter** [comment]
Oh, weird, I was not aware. Then yea, your suggestion of it as a documentation piece is good.
