### ISSUE TITLE
support arm64 architecure

### ISSUE THREAD

**Issue by longquan7** [c0b/docker-erlang-otp#69]
I was build docker-erlang-otp/20/slim/Dockerfile and docker-erlang-otp/20/Dockerfile on arm64 architecture successed. So I want to know that whether or not support arm64 architecture.Except docker-erlang-otp/20/alpine/Dockerfile, because there is some problem.

**Comment by c0b** [comment]
would you like to share some compilation errors? not everyone here has access to arm64 architecure; what's your use case

**Comment by longquan7** [comment]
Step 1 : FROM arm64v8/alpine:3.6
 ---> 61dcaf9bf40d
Step 2 : ENV OTP_VERSION "20.0.4"
 ---> Using cache
 ---> 288d76209584
Step 3 : RUN set -xe    && OTP_DOWNLOAD_URL="https://github.com/erlang/otp/archive/OTP-${OTP_VERSION}.tar.gz"   && OTP_DOWNLOAD_SHA256="4fb811b1811561f78a128c67e40b1b774354b358a4b61a9b641f0ecb06002f66"  && apk add --no-cache --virtual .fetch-deps             curl            ca-certificates         && curl -k -fSL -o otp-src.tar.gz "$OTP_DOWNLOAD_URL"   && echo "$OTP_DOWNLOAD_SHA256  otp-src.tar.gz" | sha256sum -c -    && apk add --virtual .build-deps                gcc             g++             libc-dev                linux-headers              make            autoconf                ncurses-dev             openssl-dev             unixodbc-dev            lksctp-tools-dev                tar     && export ERL_TOP="/usr/src/otp_src_${OTP_VERSION%%@*}"    && mkdir -vp $ERL_TOP   && tar -xzf otp-src.tar.gz -C $ERL_TOP --strip-components=1     && rm otp-src.tar.gz    && ( cd $ERL_TOP    && ./otp_build autoconf          && ./configure          && make -j$(getconf _NPROCESSORS_ONLN)          && make install )     && rm -rf $ERL_TOP      && find /usr/local -regex '/usr/local/lib/erlang/\(lib/\|erts-\).*/\(man\|doc\|obj\|c_src\|emacs\|info\|examples\)' | xargs rm -rf         && find /usr/local -name src | xargs -r find | grep -v '\.hrl$' | xargs rm -v || true      && find /usr/local -name src | xargs -r find | xargs rmdir -vp || true  && rm -rf               /usr/local/lib/erlang/erts*/lib/lib*.a          /usr/local/lib/erlang/usr/lib/lib*.a               /usr/local/lib/erlang/lib/*/lib/lib*.a  && scanelf --nobanner -E ET_EXEC -BF '%F' --recursive /usr/local | xargs strip --strip-all      && scanelf --nobanner -E ET_DYN -BF '%F' --recursive /usr/local | xargs -r strip --strip-unneeded  && runDeps=$(           scanelf --needed --nobanner --recursive /usr/local        | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }'                       | sort -u                       | xargs -r apk info --installed                         | sort -u       ) && apk add --virtual .erlang-rundeps $runDeps lksctp-tools       && apk del .fetch-deps .build-deps
 ---> Running in aa3819cea6af
+ OTP_DOWNLOAD_URL=https://github.com/erlang/otp/archive/OTP-20.0.4.tar.gz
+ OTP_DOWNLOAD_SHA256=4fb811b1811561f78a128c67e40b1b774354b358a4b61a9b641f0ecb06002f66
+ apk add --no-cache --virtual .fetch-deps curl ca-certificates
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/aarch64/APKINDEX.tar.gz
(1/5) Installing ca-certificates (20161130-r2)
(2/5) Installing libssh2 (1.8.0-r1)
(3/5) Installing libcurl (7.55.0-r0)
(4/5) Installing curl (7.55.0-r0)
(5/5) Installing .fetch-deps (0)
Executing busybox-1.26.2-r5.trigger
Executing ca-certificates-20161130-r2.trigger
OK: 5 MiB in 16 packages
+ curl -k -fSL -o otp-src.tar.gz https://github.com/erlang/otp/archive/OTP-20.0.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122    0   122    0     0    122      0 --:--:--  0:00:01 --:--:--   108
100 50.3M    0 50.3M    0     0  11861      0 --:--:--  1:14:12 --:--:-- 6761k
+ echo 4fb811b1811561f78a128c67e40b1b774354b358a4b61a9b641f0ecb06002f66  otp-src.tar.gz
+ sha256sum -c -
otp-src.tar.gz: OK
+ apk add --virtual .build-deps gcc g++ libc-dev linux-headers make autoconf ncurses-dev openssl-dev unixodbc-dev lksctp-tools-dev tar
WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.24d64ab1.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  .build-deps-0:
    masked in: cache
    satisfies: world[.build-deps]
  gcc (missing):
    required by:
  g++ (missing):
    required by:
  libc-dev (missing):
    required by:
  linux-headers (missing):
    required by:
  make (missing):
    required by:
  autoconf (missing):
    required by:
  ncurses-dev (missing):
    required by:
  openssl-dev (missing):
    required by:
  unixodbc-dev (missing):
    required by:
  lksctp-tools-dev (missing):
    required by:
  tar (missing):
    required by:
+ true
+ find /usr/local -name src
+ xargs -r find
+ xargs rmdir -vp
BusyBox v1.26.2 (2017-06-11 06:38:44 GMT) multi-call binary.

Usage: rmdir [OPTIONS] DIRECTORY...

Remove DIRECTORY if it is empty

        -p      Include parents
+ true
+ rm -rf /usr/local/lib/erlang/erts*/lib/lib*.a /usr/local/lib/erlang/usr/lib/lib*.a /usr/local/lib/erlang/lib/*/lib/lib*.a
+ scanelf --nobanner -E ET_EXEC -BF %F --recursive /usr/local
+ xargs strip --strip-all
The command '/bin/sh -c set -xe         && OTP_DOWNLOAD_URL="https://github.com/erlang/otp/archive/OTP-${OTP_VERSION}.tar.gz"   && OTP_DOWNLOAD_SHA256="4fb811b1811561f78a128c67e40b1b774354b358a4b61a9b641f0ecb06002f66"  && apk add --no-cache --virtual .fetch-deps             curl            ca-certificates         && curl -k -fSL -o otp-src.tar.gz "$OTP_DOWNLOAD_URL"      && echo "$OTP_DOWNLOAD_SHA256  otp-src.tar.gz" | sha256sum -c -         && apk add --virtual .build-deps                gcc             g++             libc-dev  linux-headers            make            autoconf                ncurses-dev             openssl-dev             unixodbc-dev            lksctp-tools-dev                tar     && export ERL_TOP="/usr/src/otp_src_${OTP_VERSION%%@*}"    && mkdir -vp $ERL_TOP   && tar -xzf otp-src.tar.gz -C $ERL_TOP --strip-components=1     && rm otp-src.tar.gz    && ( cd $ERL_TOP     && ./otp_build autoconf         && ./configure          && make -j$(getconf _NPROCESSORS_ONLN)          && make install )     && rm -rf $ERL_TOP      && find /usr/local -regex '/usr/local/lib/erlang/\(lib/\|erts-\).*/\(man\|doc\|obj\|c_src\|emacs\|info\|examples\)' | xargs rm -rf         && find /usr/local -name src | xargs -r find | grep -v '\.hrl$' | xargs rm -v || true      && find /usr/local -name src | xargs -r find | xargs rmdir -vp || true  && rm -rf               /usr/local/lib/erlang/erts*/lib/lib*.a          /usr/local/lib/erlang/usr/lib/lib*.a               /usr/local/lib/erlang/lib/*/lib/lib*.a  && scanelf --nobanner -E ET_EXEC -BF '%F' --recursive /usr/local | xargs strip --strip-all && scanelf --nobanner -E ET_DYN -BF '%F' --recursive /usr/local | xargs -r strip --strip-unneeded       && runDeps=$(           scanelf --needed --nobanner --recursive /usr/local | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }'                      | sort -u                       | xargs -r apk info --installed                         | sort -u       ) && apk add --virtual .erlang-rundeps $runDeps lksctp-tools       && apk del .fetch-deps .build-deps' returned a non-zero code: 123
root@ubuntu:~/arm64pr/docker-erlang-otp/20/alpine#

**Comment by tianon** [comment]
See https://github.com/c0b/docker-erlang-otp/pull/70 for a successful implementation of `arm64v8` support (and several others). :smile:

**Comment by longquan7** [comment]
@tianon That's great,thanks

**Comment by c0b** [comment]
close by #70 in https://hub.docker.com/r/arm64v8/erlang/
