### ISSUE TITLE
move on to buildpack-deps:stretch

### ISSUE THREAD

**Issue by c0b** [c0b/docker-erlang-otp#72]
since `stretch` is the alias of new latest of `buildpack-deps:latest` some other language images already moved on; this isn't priority but nice to have, sooner or late.

however when I had an attempt it resulted an over 1GB docker image for the default developer friendly  `erlang:latest` variant; reason is `stretch` is 210MB larger than `jessie`, see docker-library/buildpack-deps#64 hopefully can be fixed upstream.

**Comment by getong** [comment]
The stretch is 9.3 now, and I think switch to it should be made as soon as possible. The `debian:stretch`  may be our choice, and we make the deps in our dockerfile?

**Comment by c0b** [comment]
I agree; it seems not many ones care about docker-library/buildpack-deps#64 the 200MB size increase, and most other images have switched, it's better keep up

**Comment by getong** [comment]
This issue can be closed.

**Comment by c0b** [comment]
usually if you put `closes #72` literally in your commit message for #104 that would close this one automatically.
