### ISSUE TITLE
Dialyzer broken in 20.0.5?

### ISSUE THREAD

**Issue by tuncer** [c0b/docker-erlang-otp#76]
Is it possible that Dialyzer is broken/mis-packaged in 20.0.5? I use "20" for running Dialyzer on GitLab-CI and this is a new error. I used to run that CI job without issues before, and my local Dialyzer 20.0.5 works as well.

See https://gitlab.com/triqng/triq/-/jobs/33692481 from https://gitlab.com/triqng/triq/pipelines/12039078.

```
Error in process <0.302.0> with exit value:
{{badmatch,error},
 [{erl_types,type_from_form,6,[{file,"erl_types.erl"},{line,4769}]},
  {erl_types,t_form_to_string,1,[{file,"erl_types.erl"},{line,5286}]},
  {erl_types,t_form_to_string_list,2,[{file,"erl_types.erl"},{line,5301}]},
  {erl_types,t_form_to_string,1,[{file,"erl_types.erl"},{line,5298}]},
  {erl_types,t_form_to_string,1,[{file,"erl_types.erl"},{line,5235}]},
  {dialyzer_contracts,contract_to_string_1,1,
                      [{file,"dialyzer_contracts.erl"},{line,108}]},
  {dialyzer_dataflow,get_apply_fail_msg,10,
                     [{file,"dialyzer_dataflow.erl"},{line,642}]},
  {dialyzer_dataflow,handle_apply_or_call,10,
                     [{file,"dialyzer_dataflow.erl"},{line,562}]}]}
```

**Comment by c0b** [comment]
so did you try `erlang:20.0.4` doesn't have the error? or can do a binary search like is `erlang:20.0.1` good?

**Comment by tuncer** [comment]
Results from test project: https://gitlab.com/tuncer/testdia/pipelines/12225169

Image | Result | Log
------------ | ------------- |  -------------
19 (19.3.6.2) | GOOD | https://gitlab.com/tuncer/testdia/-/jobs/34274073/raw
20.0.1 | BAD | https://gitlab.com/tuncer/testdia/-/jobs/34274074/raw
20.0.2 | BAD | https://gitlab.com/tuncer/testdia/-/jobs/34274075/raw
20.0.3 | BAD | https://gitlab.com/tuncer/testdia/-/jobs/34274076/raw
20.0.4 | BAD | https://gitlab.com/tuncer/testdia/-/jobs/34274077/raw
20.0.5 | BAD | https://gitlab.com/tuncer/testdia/-/jobs/34274078/raw
20.1 | BAD | https://gitlab.com/tuncer/testdia/-/jobs/34274079/raw
20.1-alpine | BAD | https://gitlab.com/tuncer/testdia/-/jobs/34274080/raw

**Comment by tuncer** [comment]
Thanks, that was a good idea. Trying out the different otp releases for Dialyzer revealed a bug in the gitlab-ci file, which I've since resolved. The bug only surfaced after 20.x and was hidden with earlier versions.

**Comment by epretha** [comment]
@tuncer I am seeing the same problem with all the dialyzer versions included with all the OTP 20.x releases. Does this mean that we will never be able to use dialyzer in any of the OTP 20.x releases ?

**Comment by tuncer** [comment]
@epretha, Dialyzer, as used in [triq/.gitlab-ci.yml](https://gitlab.com/triq/triq/blob/master/.gitlab-ci.yml), works reliably with the image `erlang:20-alpine`. I don't recall the config bug, but I'd expect it to work with the Debian-based image, too.

**Comment by epretha** [comment]
Thanks @tuncer. But the problem happens in a Lubuntu virtualbox when running OTP 20.3 (dialyzer 3.2.4).

**Comment by filmor** [comment]
I'm seeing the exact same error on a Windows machine with OTP21.0.1, so this is probably unrelated to the docker image.
